import type { Candidate, HRStat } from "@/types";

export const mockCandidate: Candidate = {
  id: "c-001",
  name: "أحمد محمد العمري",
  nationalId: "1098765432",
  email: "ahmed.omari@email.com",
  phone: "+966 50 123 4567",
  jobTitle: "محلل بيانات أول",
  department: "إدارة التحول الرقمي",
  acceptanceDate: "2026-09-01",
  startDate: "2026-10-01",
  status: "in_progress",
  completionPercentage: 60,
  steps: [
    {
      id: "s-1",
      title: "قبول العرض",
      description: "تأكيد قبول عرض العمل الرسمي",
      status: "completed",
      order: 1,
    },
    {
      id: "s-2",
      title: "رفع المستندات",
      description: "رفع المستندات والوثائق المطلوبة",
      status: "in_progress",
      order: 2,
    },
    {
      id: "s-3",
      title: "التحقق من البيانات",
      description: "مراجعة واعتماد المستندات من قِبل الموارد البشرية",
      status: "pending",
      order: 3,
    },
    {
      id: "s-4",
      title: "التوقيع الإلكتروني",
      description: "توقيع العقد ووثائق التوظيف إلكترونياً",
      status: "pending",
      order: 4,
    },
    {
      id: "s-5",
      title: "الاستعداد للمباشرة",
      description: "استقبال معلومات اليوم الأول وتفاصيل الانطلاقة",
      status: "pending",
      order: 5,
    },
  ],
  documents: [
    {
      id: "d-1",
      name: "National ID",
      nameAr: "بطاقة الهوية الوطنية",
      required: true,
      status: "approved",
      uploadedAt: "2026-09-05",
    },
    {
      id: "d-2",
      name: "Academic Certificate",
      nameAr: "الشهادة الأكاديمية",
      required: true,
      status: "under_review",
      uploadedAt: "2026-09-06",
    },
    {
      id: "d-3",
      name: "Experience Certificate",
      nameAr: "شهادة الخبرة",
      required: true,
      status: "uploaded",
      uploadedAt: "2026-09-07",
    },
    {
      id: "d-4",
      name: "Criminal Record",
      nameAr: "صحيفة الحالة الجنائية",
      required: true,
      status: "rejected",
      uploadedAt: "2026-09-06",
      rejectionReason: "الصورة غير واضحة. يرجى إعادة رفع نسخة أوضح.",
    },
    {
      id: "d-5",
      name: "Personal Photo",
      nameAr: "الصورة الشخصية",
      required: true,
      status: "approved",
      uploadedAt: "2026-09-05",
    },
    {
      id: "d-6",
      name: "Bank Account",
      nameAr: "شهادة رقم الحساب البنكي (IBAN)",
      required: true,
      status: "not_uploaded",
    },
    {
      id: "d-7",
      name: "Medical Report",
      nameAr: "التقرير الطبي",
      required: false,
      status: "not_uploaded",
    },
  ],
};

export const mockCandidates: Candidate[] = [
  mockCandidate,
  {
    id: "c-002",
    name: "سارة عبدالله القحطاني",
    nationalId: "1087654321",
    email: "sara.q@email.com",
    phone: "+966 55 234 5678",
    jobTitle: "مسؤولة علاقات حكومية",
    department: "الشؤون الحكومية",
    acceptanceDate: "2026-09-03",
    status: "completed",
    completionPercentage: 100,
    steps: [],
    documents: [],
  },
  {
    id: "c-003",
    name: "خالد سعد الزهراني",
    nationalId: "1076543210",
    email: "khalid.z@email.com",
    phone: "+966 54 345 6789",
    jobTitle: "مهندس برمجيات",
    department: "تقنية المعلومات",
    acceptanceDate: "2026-09-10",
    status: "pending",
    completionPercentage: 15,
    steps: [],
    documents: [],
  },
  {
    id: "c-004",
    name: "نورة فهد الشمري",
    nationalId: "1065432109",
    email: "noura.sh@email.com",
    phone: "+966 56 456 7890",
    jobTitle: "محاسب مالي",
    department: "الشؤون المالية",
    acceptanceDate: "2026-09-08",
    status: "under_review",
    completionPercentage: 80,
    steps: [],
    documents: [],
  },
  {
    id: "c-005",
    name: "عمر محمد الحربي",
    nationalId: "1054321098",
    email: "omar.h@email.com",
    phone: "+966 50 567 8901",
    jobTitle: "مستشار قانوني",
    department: "الشؤون القانونية",
    acceptanceDate: "2026-08-25",
    status: "rejected",
    completionPercentage: 40,
    steps: [],
    documents: [],
  },
];

export const mockHRStats: HRStat = {
  total: 48,
  completed: 12,
  inProgress: 19,
  pendingAction: 11,
  rejected: 6,
};
